"""Import all model modules to trigger registration."""

from exporter.models import all_minilm_l6_v2  # noqa: F401
from exporter.models import all_minilm_l12_v2  # noqa: F401
from exporter.models import all_mpnet_base_v2  # noqa: F401
from exporter.models import resnet50_v1_7  # noqa: F401
from exporter.models import efficientnet_lite4  # noqa: F401
from exporter.models import yolov8n  # noqa: F401
from exporter.models import yolo26n  # noqa: F401
from exporter.models import distilbert_sst2  # noqa: F401
from exporter.models import ms_marco_minilm  # noqa: F401
from exporter.models import wav2vec2_base_960h  # noqa: F401
from exporter.models import silero_vad  # noqa: F401
from exporter.models import clip_vit_base_patch32  # noqa: F401
from exporter.models import craft_mlt_25k  # noqa: F401
from exporter.models import phi_3_mini  # noqa: F401
from exporter.models import deepseek_r1_qwen_1_5b  # noqa: F401
from exporter.models import whisper_small  # noqa: F401
from exporter.models import phi_3_5_vision  # noqa: F401
from exporter.models import gpt2  # noqa: F401
from exporter.models import smollm2_360m_instruct  # noqa: F401
from exporter.models import smollm2_1_7b_instruct  # noqa: F401
from exporter.models import qwen2_5_1_5b_instruct  # noqa: F401
from exporter.models import gemma_2_2b_it  # noqa: F401
from exporter.models import tinyllama_1_1b_chat  # noqa: F401
from exporter.models import flan_t5_small  # noqa: F401
from exporter.models import flan_t5_base  # noqa: F401
from exporter.models import flan_t5_large  # noqa: F401
from exporter.models import distilbart_cnn_12_6  # noqa: F401
from exporter.models import bart_large_cnn  # noqa: F401
from exporter.models import opus_mt_en_fr  # noqa: F401
from exporter.models import opus_mt_en_es  # noqa: F401
from exporter.models import opus_mt_en_de  # noqa: F401
from exporter.models import coedit_base  # noqa: F401
from exporter.models import coedit_large  # noqa: F401
from exporter.models import t5_small_awesome_text2sql  # noqa: F401
from exporter.models import t5_text2sql_spider  # noqa: F401
from exporter.models import distilbert_ner  # noqa: F401
from exporter.models import bert_base_ner  # noqa: F401
from exporter.models import bge_base_en_v1_5  # noqa: F401
from exporter.models import gte_base_en_v1_5  # noqa: F401
