import shutil
from pathlib import Path

from exporter.base import ExportedModel
from exporter.registry import register


class FlanT5Small(ExportedModel):
    name = "flan-t5-small"
    repo_id = "inference4j/flan-t5-small"
    source_repo = "google/flan-t5-small"

    def stage(self, staging_dir: Path) -> None:
        import numpy as np
        import onnxruntime as ort
        from huggingface_hub import hf_hub_download
        from optimum.exporters.onnx import main_export

        model_id = "google/flan-t5-small"

        print("  Exporting Flan-T5 Small to ONNX (encoder-decoder with KV cache)...")
        main_export(
            model_name_or_path=model_id,
            output=staging_dir,
            task="text2text-generation-with-past",
            no_post_process=False,
        )

        # Clean up non-essential files generated by optimum
        for name in ("decoder_model_merged.onnx", "generation_config.json",
                     "added_tokens.json", "tokenizer_config.json",
                     "special_tokens_map.json", "sentencepiece.bpe.model"):
            p = staging_dir / name
            if p.exists():
                p.unlink()

        # Rename decoder_with_past_model.onnx to match Java expectations
        dwp = staging_dir / "decoder_with_past_model.onnx"
        if not dwp.exists():
            # Optimum may use different naming
            for candidate in ("decoder_with_past.onnx",):
                p = staging_dir / candidate
                if p.exists():
                    p.rename(dwp)
                    break

        # Copy config.json from HuggingFace (optimum may not keep it)
        config_dst = staging_dir / "config.json"
        if not config_dst.exists():
            src = hf_hub_download(repo_id=model_id, filename="config.json")
            shutil.copy2(src, config_dst)
            print("  Copied config.json")

        # Ensure tokenizer.json exists (needed by SentencePieceBpeTokenizer)
        tok_dst = staging_dir / "tokenizer.json"
        if not tok_dst.exists():
            src = hf_hub_download(repo_id=model_id, filename="tokenizer.json")
            shutil.copy2(src, tok_dst)
            print("  Copied tokenizer.json")

        # Validate export
        _validate_encoder_decoder(staging_dir)

    def render_card(self) -> str:
        return """\
---
library_name: onnx
tags:
  - text2text-generation
  - t5
  - flan-t5
  - encoder-decoder
  - onnx
  - inference4j
license: apache-2.0
pipeline_tag: text2text-generation
---

# Flan-T5 Small — ONNX

ONNX export of [Flan-T5 Small](https://huggingface.co/google/flan-t5-small) \
(77M parameters) with encoder-decoder architecture and KV cache support.

Converted for use with [inference4j](https://github.com/inference4j/inference4j), \
an inference-only AI library for Java.

## Original Source

- **Repository:** [google/flan-t5-small](https://huggingface.co/google/flan-t5-small)
- **License:** Apache 2.0

## Usage with inference4j

```java
// Summarization
try (var gen = FlanT5TextGenerator.flanT5Small().build()) {
    System.out.println(gen.summarize("Long article text..."));
}

// Translation
try (var gen = FlanT5TextGenerator.flanT5Small().build()) {
    System.out.println(gen.translate("Hello!", Language.EN, Language.FR));
}
```

## Model Details

| Property | Value |
|----------|-------|
| Architecture | T5 encoder-decoder (77M parameters) |
| Tasks | Summarization, translation, grammar correction, text-to-SQL |
| Tokenizer | SentencePiece (32,128 tokens) |
| Original framework | PyTorch (transformers) |
| Export method | Hugging Face Optimum (encoder-decoder with KV cache) |

## License

This model is licensed under the [Apache License 2.0](https://www.apache.org/licenses/LICENSE-2.0). \
Original model by [Google](https://huggingface.co/google).
"""


def _validate_encoder_decoder(staging_dir: Path) -> None:
    """Validate that all three encoder-decoder ONNX models exist and load."""
    import numpy as np
    import onnxruntime as ort

    for name in ("encoder_model.onnx", "decoder_model.onnx",
                 "decoder_with_past_model.onnx"):
        path = staging_dir / name
        assert path.exists(), f"Missing {name}"
        session = ort.InferenceSession(str(path))
        input_names = [i.name for i in session.get_inputs()]
        output_names = [o.name for o in session.get_outputs()]
        print(f"  {name}:")
        print(f"    Inputs: {input_names}")
        print(f"    Outputs: {output_names[:5]}...")
        size_mb = path.stat().st_size / (1024 * 1024)
        print(f"    Size: {size_mb:.1f} MB")

    # Quick encoder test
    encoder = ort.InferenceSession(str(staging_dir / "encoder_model.onnx"))
    dummy_ids = np.array([[1, 2, 3]], dtype=np.int64)
    dummy_mask = np.ones_like(dummy_ids)
    result = encoder.run(None, {"input_ids": dummy_ids,
                                "attention_mask": dummy_mask})
    print(f"  Encoder output shape: {result[0].shape}")

    print("  Validation OK")


register(FlanT5Small())
