import shutil
from pathlib import Path

from exporter.base import ExportedModel
from exporter.registry import register


class Qwen2_5_1_5B_Instruct(ExportedModel):
    name = "qwen2.5-1.5b-instruct"
    repo_id = "inference4j/qwen2.5-1.5b-instruct"
    source_repo = "Qwen/Qwen2.5-1.5B-Instruct"

    def stage(self, staging_dir: Path) -> None:
        import numpy as np
        import onnxruntime as ort
        from huggingface_hub import hf_hub_download
        from optimum.exporters.onnx import main_export

        model_id = "Qwen/Qwen2.5-1.5B-Instruct"

        # Export with optimum (merged model with KV cache, FP16 weights)
        print("  Exporting Qwen2.5-1.5B-Instruct to ONNX (FP16) with KV cache...")
        main_export(
            model_name_or_path=model_id,
            output=staging_dir,
            task="text-generation-with-past",
            no_post_process=False,
            dtype="fp16",
        )

        # Rename merged model to model.onnx
        target = staging_dir / "model.onnx"
        if not target.exists():
            merged = staging_dir / "decoder_model_merged.onnx"
            if merged.exists():
                # Also rename the external data file if present
                merged_data = staging_dir / "decoder_model_merged.onnx_data"
                if merged_data.exists():
                    merged_data.rename(staging_dir / "model.onnx_data")
                    print("  Renamed decoder_model_merged.onnx_data -> model.onnx_data")
                merged.rename(target)
                print("  Renamed decoder_model_merged.onnx -> model.onnx")

                # Update the external data reference inside the ONNX file
                import onnx
                model = onnx.load(str(target), load_external_data=False)
                for tensor in model.graph.initializer:
                    if tensor.data_location == onnx.TensorProto.EXTERNAL:
                        for entry in tensor.external_data:
                            if entry.key == "location" and "decoder_model_merged" in entry.value:
                                entry.value = "model.onnx_data"
                onnx.save(model, str(target))
                print("  Updated external data references in model.onnx")
            else:
                for candidate in sorted(staging_dir.glob("*.onnx")):
                    candidate.rename(target)
                    print(f"  Renamed {candidate.name} -> model.onnx")
                    break

        # Clean up intermediate model files generated by optimum
        for f in list(staging_dir.glob("decoder_model*")):
            f.unlink()
            print(f"  Removed {f.name}")

        # Copy tokenizer files from HuggingFace
        for filename in ("vocab.json", "merges.txt", "config.json",
                         "tokenizer_config.json", "special_tokens_map.json"):
            dst = staging_dir / filename
            if not dst.exists():
                src = hf_hub_download(repo_id=model_id, filename=filename)
                shutil.copy2(src, dst)
                print(f"  Copied {filename}")

        # Remove non-essential files generated by optimum
        for name in ("tokenizer.json", "generation_config.json",
                     "added_tokens.json"):
            p = staging_dir / name
            if p.exists():
                p.unlink()

        # Validate export
        print("  Validating export...")
        session = ort.InferenceSession(str(target))
        input_names = [i.name for i in session.get_inputs()]
        output_names = [o.name for o in session.get_outputs()]
        print(f"    Inputs ({len(input_names)}): {input_names[:6]}...")
        print(f"    Outputs ({len(output_names)}): {output_names[:4]}...")

        assert "input_ids" in input_names
        assert "attention_mask" in input_names
        assert any("past_key_values" in n for n in input_names), \
            f"No past_key_values in inputs: {input_names}"
        assert "logits" in output_names
        assert any("present" in n for n in output_names), \
            f"No present in outputs: {output_names}"

        # Count KV cache layers
        kv_layers = sum(1 for n in input_names
                        if n.startswith("past_key_values") and n.endswith(".key"))
        print(f"    KV cache layers: {kv_layers}")

        # Quick inference test
        prompt_ids = np.array([[1]], dtype=np.int64)
        attention = np.ones_like(prompt_ids)
        feeds = {"input_ids": prompt_ids, "attention_mask": attention}

        # Add position_ids if expected
        if "position_ids" in input_names:
            feeds["position_ids"] = np.zeros_like(prompt_ids)

        # Add empty KV cache (use FP16 if the model expects it)
        for inp in session.get_inputs():
            if inp.name.startswith("past_key_values"):
                shape = list(inp.shape)
                shape = [s if isinstance(s, int) else 0 for s in shape]
                shape[0] = 1  # batch size
                dtype = np.float16 if inp.type == "tensor(float16)" else np.float32
                feeds[inp.name] = np.zeros(shape, dtype=dtype)

        results = session.run(None, feeds)
        logits = results[0]
        print(f"    Logits shape: {logits.shape}")
        assert logits.shape[-1] == 151936, \
            f"Expected vocab size 151936, got {logits.shape[-1]}"
        print("  Validation OK")

        # Report total model size
        total_mb = sum(
            f.stat().st_size for f in staging_dir.glob("model.onnx*")
        ) / (1024 * 1024)
        print(f"  Export complete: {total_mb:.0f} MB total (FP16)")

    def render_card(self) -> str:
        return """\
---
library_name: onnx
tags:
  - text-generation
  - qwen2
  - onnx
  - inference4j
license: apache-2.0
pipeline_tag: text-generation
---

# Qwen2.5-1.5B-Instruct — ONNX (FP16)

ONNX export of [Qwen2.5-1.5B-Instruct](https://huggingface.co/Qwen/Qwen2.5-1.5B-Instruct) \
(1.5B parameters, FP16 weights) with KV cache support for efficient autoregressive generation.

Converted for use with [inference4j](https://github.com/inference4j/inference4j), \
an inference-only AI library for Java.

## Original Source

- **Repository:** [Qwen/Qwen2.5-1.5B-Instruct](https://huggingface.co/Qwen/Qwen2.5-1.5B-Instruct)
- **License:** Apache 2.0

## Usage with inference4j

```java
try (var gen = OnnxTextGenerator.qwen2().build()) {
    GenerationResult result = gen.generate("What is Java?");
    System.out.println(result.text());
}
```

## Model Details

| Property | Value |
|----------|-------|
| Architecture | Qwen2ForCausalLM (1.5B parameters, 28 layers, 1536 hidden, 12 heads, 2 KV heads) |
| Task | Text generation (instruction-tuned) |
| Precision | FP16 |
| Context length | 32,768 tokens |
| Vocabulary | 151,936 tokens (BPE) |
| Chat template | ChatML (`<|im_start|>user`...`<|im_end|>`) |
| Original framework | PyTorch (transformers) |
| Export method | Hugging Face Optimum (with KV cache, FP16) |

## License

This model is licensed under the [Apache License 2.0](https://www.apache.org/licenses/LICENSE-2.0). \
Original model by [Qwen Team, Alibaba Cloud](https://huggingface.co/Qwen).
"""


register(Qwen2_5_1_5B_Instruct())
