import shutil
from pathlib import Path

from exporter.base import ExportedModel
from exporter.registry import register


class SmolLM2_360M_Instruct(ExportedModel):
    name = "smollm2-360m-instruct"
    repo_id = "inference4j/smollm2-360m-instruct"
    source_repo = "HuggingFaceTB/SmolLM2-360M-Instruct"

    def stage(self, staging_dir: Path) -> None:
        import numpy as np
        import onnxruntime as ort
        from huggingface_hub import hf_hub_download
        from optimum.exporters.onnx import main_export

        model_id = "HuggingFaceTB/SmolLM2-360M-Instruct"

        # Export with optimum (merged model with KV cache)
        print("  Exporting SmolLM2-360M-Instruct to ONNX with KV cache...")
        main_export(
            model_name_or_path=model_id,
            output=staging_dir,
            task="text-generation-with-past",
            no_post_process=False,
        )

        # Rename merged model to model.onnx
        target = staging_dir / "model.onnx"
        if not target.exists():
            merged = staging_dir / "decoder_model_merged.onnx"
            if merged.exists():
                merged.rename(target)
                print("  Renamed decoder_model_merged.onnx -> model.onnx")
            else:
                for candidate in sorted(staging_dir.glob("*.onnx")):
                    candidate.rename(target)
                    print(f"  Renamed {candidate.name} -> model.onnx")
                    break

        # Clean up intermediate model files generated by optimum
        for f in staging_dir.glob("decoder_model*.onnx"):
            f.unlink()
            print(f"  Removed {f.name}")

        # Copy tokenizer files from HuggingFace
        for filename in ("vocab.json", "merges.txt", "config.json",
                         "tokenizer_config.json", "special_tokens_map.json"):
            dst = staging_dir / filename
            if not dst.exists():
                src = hf_hub_download(repo_id=model_id, filename=filename)
                shutil.copy2(src, dst)
                print(f"  Copied {filename}")

        # Remove non-essential files generated by optimum
        for name in ("tokenizer.json", "generation_config.json",
                     "added_tokens.json"):
            p = staging_dir / name
            if p.exists():
                p.unlink()

        # Validate export
        print("  Validating export...")
        session = ort.InferenceSession(str(target))
        input_names = [i.name for i in session.get_inputs()]
        output_names = [o.name for o in session.get_outputs()]
        print(f"    Inputs ({len(input_names)}): {input_names[:6]}...")
        print(f"    Outputs ({len(output_names)}): {output_names[:4]}...")

        assert "input_ids" in input_names
        assert "attention_mask" in input_names
        assert any("past_key_values" in n for n in input_names), \
            f"No past_key_values in inputs: {input_names}"
        assert "logits" in output_names
        assert any("present" in n for n in output_names), \
            f"No present in outputs: {output_names}"

        # Count KV cache layers
        kv_layers = sum(1 for n in input_names
                        if n.startswith("past_key_values") and n.endswith(".key"))
        print(f"    KV cache layers: {kv_layers}")

        # Quick inference test
        prompt_ids = np.array([[1]], dtype=np.int64)  # BOS token
        attention = np.ones_like(prompt_ids)
        feeds = {"input_ids": prompt_ids, "attention_mask": attention}

        # Add position_ids if expected
        if "position_ids" in input_names:
            feeds["position_ids"] = np.zeros_like(prompt_ids)

        # Add empty KV cache
        for inp in session.get_inputs():
            if inp.name.startswith("past_key_values"):
                shape = list(inp.shape)
                shape = [s if isinstance(s, int) else 0 for s in shape]
                shape[0] = 1  # batch size
                feeds[inp.name] = np.zeros(shape, dtype=np.float32)

        results = session.run(None, feeds)
        logits = results[0]
        print(f"    Logits shape: {logits.shape}")
        assert logits.shape[-1] == 49152, \
            f"Expected vocab size 49152, got {logits.shape[-1]}"
        print("  Validation OK")

        size_mb = target.stat().st_size / (1024 * 1024)
        print(f"  Export complete: model.onnx ({size_mb:.1f} MB)")

    def render_card(self) -> str:
        return """\
---
library_name: onnx
tags:
  - text-generation
  - smollm2
  - llama
  - onnx
  - inference4j
license: apache-2.0
pipeline_tag: text-generation
---

# SmolLM2-360M-Instruct — ONNX

ONNX export of [SmolLM2-360M-Instruct](https://huggingface.co/HuggingFaceTB/SmolLM2-360M-Instruct) \
(360M parameters) with KV cache support for efficient autoregressive generation.

Converted for use with [inference4j](https://github.com/inference4j/inference4j), \
an inference-only AI library for Java.

## Original Source

- **Repository:** [HuggingFaceTB/SmolLM2-360M-Instruct](https://huggingface.co/HuggingFaceTB/SmolLM2-360M-Instruct)
- **License:** Apache 2.0

## Usage with inference4j

```java
try (var gen = OnnxTextGenerator.smolLM2().build()) {
    GenerationResult result = gen.generate("What is Java?");
    System.out.println(result.text());
}
```

## Model Details

| Property | Value |
|----------|-------|
| Architecture | LlamaForCausalLM (360M parameters, 32 layers, 960 hidden, 15 heads, 5 KV heads) |
| Task | Text generation (instruction-tuned) |
| Context length | 8192 tokens |
| Vocabulary | 49,152 tokens (BPE) |
| Chat template | ChatML (`<|im_start|>user`...`<|im_end|>`) |
| Original framework | PyTorch (transformers) |
| Export method | Hugging Face Optimum (with KV cache) |

## License

This model is licensed under the [Apache License 2.0](https://www.apache.org/licenses/LICENSE-2.0). \
Original model by [HuggingFace](https://huggingface.co/HuggingFaceTB).
"""


register(SmolLM2_360M_Instruct())
